default/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('poll/', views.PollList.as_view()),
    path('poll/<int:pk>/', views.PollView.as_view()),
    path('option/<int:oid>/', views.PollVote.as_view()),
    path('poll/create/', views.PollCreate.as_view()),
    path("poll/<int:pk>/edit/", views.PollEdit.as_view()),
    path('poll/<int:pid>/add/', views.OptionCreate.as_view()),
    path("option/<int:pk>/edit/", views.OptionEdit.as_view()),
    path("option/<int:pk>/delete/", views.OptionDelete.as_view()),
    path("poll/<int:pk>/delete/",views.PollDelete.as_view()),
]

poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('default.urls'))
]

default/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    title = models.CharField('投票主題', max_length=100)
    desc = models.TextField('說明', max_length=512)
    created = models.DateField('建立時間', auto_now_add=True)

    def __str__(self):
        return"{}: {}".format(self.id, self.title)
    
class Option(models.Model):
    poll_id = models.IntegerField('所屬投票主題')
    title = models.CharField('選項文字', max_length=100)
    count = models.IntegerField('票數', default=0)

    def __str__(self):
        return"{}: ({}) {}".format(self.id, self.poll_id, self.title)

default/views.py
from django.shortcuts import render
from .models import Poll, Option
from django.views.generic import ListView, DetailView, RedirectView, CreateView, UpdateView, DeleteView

# Create your views here.
class PollCreate(CreateView):
    model = Poll
    fields = ['title', 'desc']
    success_url = '/poll/'

class PollEdit(UpdateView):
    model = Poll
    fields = ['title', 'desc']
    success_url = '/poll/'

class OptionCreate(CreateView):
    model = Option
    fields = ['title', 'count']

    def get_success_url(self):
        return '/poll/{}/'.format(self.kwargs['pid'])

    def form_valid(self, form):
        form.instance.poll_id = self.kwargs['pid']
        return super().form_valid(form)

class OptionEdit(UpdateView):
    model = Option
    fields = ['title', 'count']

    def get_success_url(self):
        return '/poll/{}/'.format(self.object.poll_id)

class OptionDelete(DeleteView):
    model = Option
    template_name = 'confirm_delete.html'

    def get_success_url(self):
         return '/poll/{}/'.format(self.object.poll_id)

class PollDelete(DeleteView):
    model = Poll
    success_url = "/poll/"
    
class PollList(ListView):
    model = Poll

class PollView(DetailView):
    model = Poll

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['option_list'] = Option.objects.filter(poll_id = self.kwargs['pk'])
        return data

class PollVote(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        opt = Option.objects.get(id=self.kwargs['oid'])
        opt.count = opt.count +1
        opt.save()
        return '/poll/{}/'.format(opt.poll_id)

default/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}

    {% endblock content%}
</body>
</html>

default/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<p>確定要刪除 {{ object }} 嗎? </p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="確認刪除">
</form>
{% endblock %}

default/templates/default/option_form.html
{% extends "base.html" %}

{% block content %}
<h1>新增投票主題</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <input type="submit" value="送出">
    </table>
</form>
  
{% endblock content %}

default/templates/default/poll.list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>投票主題</h1>

    <ul>
    {% for poll in poll_list %}
        <li>
            {{ poll.created }}
            <a href="/poll/{{ poll.id }}/">{{ poll.subject }}</a>
        </li>
    {% endfor%}
    </ul>

</body>
</html>

default/templates/default/poll_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/poll/">投票主題列表</a>
    <h1>{{ poll.title }}</h1>
    <a href="/poll/{{ poll.id }}/edit/">修改</a>
    <p>{{ poll.desc|linebreaks }}</p>

    <a href = "/poll/{{ poll.id }}/add/">新增選項</a>
    <ul>
        {% for option in option_list %}
        <li>
            <a href="/option/{{option.id}}/">{{ option.title }}</a> 
            : {{ option.count }} 票
                <a href="/option/{{option.id}}/edit/">修改</a>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

default/templates/default/poll_form.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <input type="submit" value="submit">
    </table>
</form>
  
{% endblock content %}

default/templates/default/poll_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>投票主題</h1>
    <a href= "/poll/create/">新增投票主題</a>
    <ul>
    {% for poll in poll_list %}
        <li>
            {{ poll.created }}
            <a href="/poll/{{ poll.id }}/">{{ poll.title }}</a>
        </li>
    {% endfor%}
    </ul>

</body>
</html>

default/templates/poll_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>投票主題</h1>

    <ul>
    {% for poll in poll_list %}
        <li>{{ poll.created }}{{ poll.subject }}</li>
    {% endfor%}
    </ul>

</body>
</html>